name: Cleanup Old Resources

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ticket-hub-app
  GITHUB_PACKAGE_NAME: ticket-hub-main-now1   # explicitly define your package name

jobs:
  cleanup-ecr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Delete old ECR images
        run: |
          # Keep only the latest 10 images
          aws ecr describe-images \
            --repository-name $ECR_REPOSITORY \
            --query 'sort_by(imageDetails,&imagePushedAt)[:-10].imageDigest' \
            --output text | \
          while read digest; do
            if [ "$digest" != "None" ] && [ -n "$digest" ]; then
              echo "Deleting image with digest: $digest"
              aws ecr batch-delete-image \
                --repository-name $ECR_REPOSITORY \
                --image-ids imageDigest="$digest" || true
            fi
          done
          
  cleanup-github-packages:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      
    steps:
      - name: Delete old GitHub packages
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.GITHUB_PACKAGE_NAME }}
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: true
